### ISSUE TITLE
2021アドベントカレンダーで見かけたアクセシビリティ関連の記事

### ISSUE THREAD

**Issue by yamanoku** [yamanoku/awesome-japanese-a11y-companies#21]
まとめて順次アップしていく

---

（コメント追記してくれる人向け）掲載のルールです

- 日本に拠点がある
- テクノロジー企業である
- アクセシビリティに取り組んでいることが分かる事例（アクセシビリティ方針、事業サービス、チーム、記事リンク等）
  - 個人でやってみた系、技術の紹介のものは含めないようにする
- 2021年のアドベントカレンダー記事である

**Comment by yamanoku** [comment]
[2021年に行ったアクセシビリティやっていき - BASEプロダクトチームブログ(https://devblog.thebase.in/entry/2021/12/06/111517)

**Comment by yamanoku** [comment]
[日経電子版アクセシビリティの取り組み — HACK The Nikkei](https://hack.nikkei.com/blog/advent20211204/)

**Comment by yamanoku** [comment]
[2021年、freeeのアクセシビリティを振り返る｜magi｜note](https://note.com/magi1125/n/ncc519a490f6c)

**Comment by kuma0520** [comment]
[みんなが使えるカルーセルUIを考える | CyberAgent Developers Blog](https://developers.cyberagent.co.jp/blog/archives/32842/)

**Comment by kuma0520** [comment]
[Webアクセシビリティを考慮したチェックボックス・ラジオボタン・セレクトボックス・タブ・アコーディオンの実装](https://www.willstyle.co.jp/blog/4841/)

**Comment by magi1125** [comment]
[機械学習を使ってUIを補完するAppleの研究の紹介](https://tech.dely.jp/entry/2021/12/02/100000)

**Comment by yamanoku** [comment]
[新卒配属後31件のアクセシビリティ改善をした話 | CyberAgent Developers Blog](https://developers.cyberagent.co.jp/blog/archives/33026/)

**Comment by yamanoku** [comment]
[2021年、アメブロのアクセシビリティを振り返る | CyberAgent Developers Blog](https://developers.cyberagent.co.jp/blog/archives/33143/)

**Comment by yamanoku** [comment]
[react-slickでカルーセルをコントロールするUIを改造してアクセシビリティ対応する方法 - Qiita](https://qiita.com/gilly/items/cd70d70b279334560f8b)

**Comment by yamanoku** [comment]
[Accessibility Testing 101 | Mercari Engineering](https://engineering.mercari.com/en/blog/entry/20211215-accessibility-testing-101/)

**Comment by yamanoku** [comment]
[緑(Succeed)と赤(Failed)を区別する - よりinclusiveなCircleCIを目指して - Qiita](https://qiita.com/mfunaki/items/c43e79a37cab759237e9)

**Comment by yamanoku** [comment]
[Qiitaのユーザー体験を良くするために新しい部署を立ち上げた話 - Qiita](https://qiita.com/xrxoxcxox/items/1d814c4d23e20829234c#%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B7%E3%83%93%E3%83%AA%E3%83%86%E3%82%A3%E3%81%AE%E5%90%91%E4%B8%8A)

Qiita株式会社

> ### アクセシビリティの向上

**Comment by yamanoku** [comment]
[動画のアクセシビリティ - Yahoo! JAPAN Tech Blog](https://techblog.yahoo.co.jp/entry/2021121930233808/)

Yahoo! Japan
取組事例ではないのでネタとして

**Comment by yamanoku** [comment]
[アクセシビリティ本の輪読会をした話 - トレタ開発者ブログ](https://tech.toreta.in/entry/2021/12/19/010126)

株式会社トレタ

**Comment by yamanoku** [comment]
[2021年、サイバーエージェントのアクセシビリティを振り返る | CyberAgent Developers Blog](https://developers.cyberagent.co.jp/blog/archives/33931/)

サイバーエージェント

**Comment by yamanoku** [comment]
[トップページリニューアルのために見直した4つのこと。｜ハラ｜note](https://note.com/haraharam/n/n59c14f76a76c#89d28935-a965-40d3-a0b6-e54908979cbd)

クラウドワークス

> 3. カラーコントラスト比の見直し

**Comment by yamanoku** [comment]
[freee 社のアクセシビリティガイドラインとチェックリストを丸ごと導入した - hey Product Blog](https://tech.hey.jp/entry/2021/12/24/112102)

hey

**Comment by yamanoku** [comment]
一旦ここまで（一部）をリポジトリに追加していきます。
教えていただいた方ありがとうございました！
